In [2]:
import numpy as np


In [3]:
array = np.array([1,2,3])

In [4]:
len(array)

3

In [6]:
array.shape


(3,)

In [5]:
a = np.zeros(10, dtype=np.uint8)
a[2] = 3


In [6]:
a

array([0, 0, 3, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [7]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
b = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])

In [9]:
b.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [12]:
import os
os.listdir(r"C:\Users\hongxiao95\Documents\Code\2023\number_ocr\source_data\train")

['0.1.jpg',
 '0.10.jpg',
 '0.11.jpg',
 '0.12.jpg',
 '0.13.jpg',
 '0.14.jpg',
 '0.15.jpg',
 '0.16.jpg',
 '0.2.jpg',
 '0.3.jpg',
 '0.4.jpg',
 '0.5.jpg',
 '0.6.jpg',
 '0.7.jpg',
 '0.8.jpg',
 '0.9.jpg',
 '1.1.jpg',
 '1.10.jpg',
 '1.11.jpg',
 '1.12.jpg',
 '1.13.jpg',
 '1.14.jpg',
 '1.15.jpg',
 '1.16.jpg',
 '1.2.jpg',
 '1.3.jpg',
 '1.4.jpg',
 '1.5.jpg',
 '1.6.jpg',
 '1.7.jpg',
 '1.8.jpg',
 '1.9.jpg',
 '2.1.jpg',
 '2.10.jpg',
 '2.11.jpg',
 '2.12.jpg',
 '2.13.jpg',
 '2.14.jpg',
 '2.15.jpg',
 '2.16.jpg',
 '2.2.jpg',
 '2.3.jpg',
 '2.4.jpg',
 '2.5.jpg',
 '2.6.jpg',
 '2.7.jpg',
 '2.8.jpg',
 '2.9.jpg',
 '3.1.jpg',
 '3.10.jpg',
 '3.11.jpg',
 '3.12.jpg',
 '3.13.jpg',
 '3.14.jpg',
 '3.15.jpg',
 '3.16.jpg',
 '3.2.jpg',
 '3.3.jpg',
 '3.4.jpg',
 '3.5.jpg',
 '3.6.jpg',
 '3.7.jpg',
 '3.8.jpg',
 '3.9.jpg',
 '4.1.jpg',
 '4.10.jpg',
 '4.11.jpg',
 '4.12.jpg',
 '4.13.jpg',
 '4.14.jpg',
 '4.15.jpg',
 '4.16.jpg',
 '4.2.jpg',
 '4.3.jpg',
 '4.4.jpg',
 '4.5.jpg',
 '4.6.jpg',
 '4.7.jpg',
 '4.8.jpg',
 '4.9.jpg',
 '5.1

In [25]:
from enum import Enum
import numpy as np

class Tag(Enum):
    '''
    描述一个样本的类别，包括类别名称和onehot编码
    '''
    @staticmethod
    def _get_one_hot(number):
        if number not in list(range(10)):
            return np.zeros(10, dtype=np.uint8)
        res = np.zeros(10, dtype=np.uint8)
        res[number] = 1
        return res

    ZERO = (0, _get_one_hot(0))
    ONE = (1, _get_one_hot(1))
    TWO = (2, _get_one_hot(2))
    THREE = (3, _get_one_hot(3))
    FOUR = (4, _get_one_hot(4))
    FIVE = (5, _get_one_hot(5))
    SIX = (6, _get_one_hot(6))
    SEVEN = (7, _get_one_hot(7))
    EIGHT = (8, _get_one_hot(8))
    NINE = (9, _get_one_hot(9))

    def __init__(self, num_value:int, onehot:np.ndarray):
        self.num_value = num_value
        self.onehot = onehot

TypeError: Tag.__init__() missing 1 required positional argument: 'onehot'

In [21]:
a = Tag.EIGHT
a.value

(8, array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=uint8))

In [22]:
Tag.get_by_value(7)

ValueError: Value 7 not in Tag!

In [26]:
class Tag(Enum):
    '''
    描述一个样本的类别，包括类别名称和onehot编码
    '''
    @staticmethod
    def _get_one_hot(number):
        if number not in list(range(10)):
            return np.zeros(10, dtype=np.uint8)
        res = np.zeros(10, dtype=np.uint8)
        res[number] = 1
        return res
    
    def __init__(self, num_value:int, onehot:np.ndarray):
        self.num_value = num_value
        self.onehot = onehot

    ZERO = (0, _get_one_hot(0))
    ONE = (1, _get_one_hot(1))
    TWO = (2, _get_one_hot(2))
    THREE = (3, _get_one_hot(3))
    FOUR = (4, _get_one_hot(4))
    FIVE = (5, _get_one_hot(5))
    SIX = (6, _get_one_hot(6))
    SEVEN = (7, _get_one_hot(7))
    EIGHT = (8, _get_one_hot(8))
    NINE = (9, _get_one_hot(9))

    @classmethod
    def get_by_value(cls, num_value):
        for member in cls:
            if member.num_value == num_value:
                return member
        else:
            raise ValueError(f"Value {num_value} not in Tag!")

In [27]:
Tag.get_by_value(5)

<Tag.FIVE: (5, array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=uint8))>

In [39]:
def load_samples_from_file(path:str, file_filter:str = ".jpg"):
    file_list = tuple(filter(lambda x : x.lower().endswith(file_filter), os.listdir(path)))
    file_list = [path + os.path.sep + x for x in file_list]
    return file_list

a = load_samples_from_file(r"C:\Users\hongxiao95\Documents\Code\2023\number_ocr\source_data\train")

In [43]:
import cv2
img_0 = cv2.imread(a[0])
cv2.cvtColor(img_0, cv2.COLOR_BGR2GRAY)

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [48]:
img = cv2.imread(a[1], cv2.IMREAD_GRAYSCALE)
img.flatten()
len(img)

40

In [1]:
import cv2
import numpy as np
from numrec import load_samples_from_file


datas = load_samples_from_file("../source_data/train")

In [2]:
datas

In [38]:
import numpy as np
arr = np.zeros((3,2),dtype=np.float32)
def fun(x):
    x+=5

In [52]:
arr = np.full((5,3),4)
arr

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [61]:
another_arr = np.full((2,5), 6)
arr = np.concatenate((arr, another_arr,arr), axis=0)
arr


array([[4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4, 6, 6],
       [4, 4, 4,

In [63]:
arr.shape[0]

50

In [1]:
import numpy as np


In [4]:
arr = np.random.randint(10,255,size=(3,5))
arr



array([[ 77, 164,  61,  16, 166],
       [ 96, 186,  46,  93, 200],
       [149, 172,  68,  37,  10]])

In [5]:
arr[arr < 60] = 70
arr

array([[ 77, 164,  61,  70, 166],
       [ 96, 186,  70,  93, 200],
       [149, 172,  68,  70,  70]])

In [7]:
arr[:,3] > 200

array([False, False, False])

In [13]:
bias = np.array([[2,3,4]]).T
newarr = newarr + bias
newarr

array([[ 85, 172,  69,  78, 174],
       [108, 198,  82, 105, 212],
       [165, 188,  84,  86,  86]])

In [9]:
bias

array([2, 3, 4])

In [15]:
arr = np.random.randint(-50,50, size=(4,6))
arr

array([[-41, -42,  32,  32,  11, -47],
       [-21,  15, -32,  24, -24, -36],
       [ 11,  35,   5,   5,  -9,  24],
       [ -4, -35, -43,  -5, -24,  10]])

In [19]:
maxar = np.max(arr, axis=0)
arr = arr - maxar


array([[-52, -77,   0,   0,   0, -71],
       [-32, -20, -64,  -8, -35, -60],
       [  0,   0, -27, -27, -20,   0],
       [-15, -70, -75, -37, -35, -14]])

In [21]:
expar = np.exp(arr)
expar

array([[2.61027907e-23, 3.62514092e-34, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.46248623e-31],
       [1.26641655e-14, 2.06115362e-09, 1.60381089e-28, 3.35462628e-04,
        6.30511676e-16, 8.75651076e-27],
       [1.00000000e+00, 1.00000000e+00, 1.87952882e-12, 1.87952882e-12,
        2.06115362e-09, 1.00000000e+00],
       [3.05902321e-07, 3.97544974e-31, 2.67863696e-33, 8.53304763e-17,
        6.30511676e-16, 8.31528719e-07]])

In [22]:
rate_ar = expar / np.sum(expar, axis=0)
rate_ar

array([[2.61027827e-23, 3.62514091e-34, 1.00000000e+00, 9.99664650e-01,
        9.99999998e-01, 1.46248501e-31],
       [1.26641617e-14, 2.06115362e-09, 1.60381089e-28, 3.35350130e-04,
        6.30511675e-16, 8.75650348e-27],
       [9.99999694e-01, 9.99999998e-01, 1.87952882e-12, 1.87889852e-12,
        2.06115362e-09, 9.99999168e-01],
       [3.05902227e-07, 3.97544973e-31, 2.67863696e-33, 8.53018607e-17,
        6.30511675e-16, 8.31528028e-07]])

In [7]:
from numrec import OneHotFullLinkNetwork
from NetworkFunctions import ReLU

network = OneHotFullLinkNetwork([40,40,40], activation=ReLU, learn_rate=0.01)
network.load_samples_and_init_network("../source_data/train")

network.forward_broadcasting()



broad 1 layer
broad 1 layer
broad 1 layer
broad 1 layer
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 1. 0.]]


In [1]:
import numpy as np
arr = np.random.randint(-50,50, size=(4,6))
arr

array([[ 19,  46, -48,  28,  42,  -9],
       [  3, -42, -36,  -1, -17, -24],
       [-33, -28, -49,  -8,  -9, -16],
       [-23, -18, -23, -33,   4, -50]])

In [15]:
from NetworkFunctions import softmax

a_v = np.average(arr, axis=1).reshape(-1,1)
a_v

array([[ 13.        ],
       [-19.5       ],
       [-23.83333333],
       [-23.83333333]])

In [16]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A * B
C

array([[ 5, 12],
       [21, 32]])

In [33]:
arr = np.random.randint(-50,50, size=(4,6))
arr

array([[ -7,  47, -32,  40, -24, -18],
       [-23,  27, -20,  20,  10,  13],
       [  3,  -4, -29,  22,  48,  28],
       [-15,  31,  10,   7, -11,  14]])

In [21]:
arr.argmax(axis=0)

array([1, 2, 1, 3, 1, 1], dtype=int64)

In [22]:
real_arr = np.array([[1,0,0,0,0,1],
            [0,0,0,0,0,0],
            [0,1,1,0,0,0],
            [0,0,0,1,1,0]])

In [28]:
aa = arr.argmax(axis=0)
ra = real_arr.argmax(axis=0)
aa[aa == ra] = 0
aa

array([1, 0, 1, 0, 1, 1], dtype=int64)

In [29]:
real_arr.shape[1]

6

In [32]:
print(f"{100.2344321687:.6}")

100.234


In [35]:
true_pos = real_arr.argmax(axis=0)
true_pos

array([0, 2, 2, 3, 3, 0], dtype=int64)

In [44]:
arr[true_pos,np.arange(arr.shape[1])]

array([ -7,  -4, -29,   7, -11, -18])

In [4]:
import time
a = time.time()
a

1701085632.3954477

In [2]:
import configparser, os
def save_config(config_dir:str = "nn_config"):
        if os.path.exists(config_dir) == False:
            os.makedirs(config_dir)
        config_file_name = config_dir + os.path.sep + "network_args.ini"

        config = configparser.ConfigParser()
        config["main"] = {
             "learn_rate":"0.05",
             "mid_normal_max":"5",
             "sample_width":"28",
             "sample_height":"28"
        }
    
        with open(config_file_name, "w") as config_file:
            config.write(config_file)

save_config("test_config")

In [3]:
import numpy as np
# 存储网络参数：每层的权重矩阵、偏置矩阵
config_dir = "test_config"
weights_file_name = config_dir + os.path.sep + "weights.npz"
bias_file_name = config_dir + os.path.sep + "biases.npz"

weights = {}
biases = {}

weights["weight_1"] = np.random.randint(10,30, (5,5))
weights["weight_2"] = np.random.randint(10,30, (5,5))
weights["weight_3"] = np.random.randint(10,30, (5,7))

biases["bias_1"] = np.random.randint(10,30, (5,5))
biases["bias_2"] = np.random.randint(10,30, (6,5))
biases["bias_3"] = np.random.randint(10,30, (4,5))


np.savez(weights_file_name, **weights)
np.savez(bias_file_name, **biases)

In [14]:
loaded = np.load("test_config/weights.npz")
arr_count = len(loaded.keys())

arrays = []

for i in range(arr_count):
    arrays.append(loaded[f"qq{i + 1}"])

for array in arrays:
    print(array)

[[24 16 19 14 22]
 [24 18 13 20 28]
 [13 22 13 14 14]
 [25 25 12 14 20]
 [22 10 18 24 23]]
[[15 25 27 25 29]
 [17 26 18 28 23]
 [25 21 27 12 16]
 [15 29 15 19 15]
 [26 29 28 24 19]]
[[18 27 15 26 10 15 24]
 [20 24 28 24 24 29 28]
 [15 29 10 24 28 23 21]
 [10 12 14 14 13 22 21]
 [10 15 13 28 25 21 12]]


In [4]:
from numrec import OneHotFullLinkNetwork

def load_config_and_init_predict_network(config_dir:str = "nn_config"):
    config_file_name = config_dir + os.path.sep + "network_args.ini"
    weights_file_name = config_dir + os.path.sep + "weights.npz"
    biases_file_name = config_dir + os.path.sep + "biases.npz"

    if os.path.exists(config_file_name) == False or os.path.exists(weights_file_name) == False or os.path.exists(biases_file_name) == False:
        raise FileNotFoundError("配置文件不全！")

    config = configparser.ConfigParser()
    config.read(config_file_name)
    learn_rate = float(config["main"]["learn_rate"])
    mid_normal_max = int(config["main"]["mid_normal_max"])
    sample_width = int(config["main"]["sample_width"])
    sample_height = int(config["main"]["sample_height"])

    weight_load = np.load(weights_file_name)
    weight_matrix = []
    for i in range(len(weight_load)):
        weight_matrix.append(weight_load[OneHotFullLinkNetwork.get_n_weight_name(i + 1)])

    bias_load = np.load(biases_file_name)
    biases_matrix = []
    for i in range(len(bias_load)):
        biases_matrix.append(bias_load[OneHotFullLinkNetwork.get_n_bias_name(i + 1)])
    
    mid_layer_sizes = [len(x) for x in biases_matrix]

    network = OneHotFullLinkNetwork(mid_layer_sizes, "ReLU", learn_rate=learn_rate, mid_normal_max=mid_normal_max, sample_shape=(sample_width, sample_height))
    #network.init_network_for_predict(weight_matrix, biases_matrix)

    return network

In [5]:
load_config_and_init_predict_network("test_config")